# Generated by Django 4.2.3 on 2023-08-21 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('Dwarf', 'Дварф'), ('Elf', 'Эльф'), ('Halfling', 'Полурослик'), ('Human', 'Человек'), ('Dragonborn', 'Драконорожденный'), ('Gnome', 'Гном'), ('Half-elf', 'Полуэльф'), ('Half-orc', 'Полуорк'), ('Tiefling', 'Тифлинг')], max_length=255)),
                ('klass', models.CharField(choices=[('Barbarian', 'Варвар'), ('Bard', 'Бард'), ('Cleric', 'Жрец'), ('Druid', 'Друид'), ('Warrior', 'Воин'), ('Monk', 'Монах'), ('Paladin', 'Паладин'), ('Ranger', 'Следопыт'), ('Rogue', 'Плут'), ('Sorcerer', 'Чародей'), ('Warlock', 'Колдун'), ('Wizard', 'Волшебник')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('men', 'муж'), ('women', 'жен')], max_length=255)),
                ('ideology', models.CharField(choices=[('LG-GD', 'Законно-доброе'), ('NT-GD', 'Нейтрально-доброе'), ('CH-GD', 'Хаотично-доброе'), ('LG-NT', 'Законно-нейтральное'), ('NT', 'Нейтральное'), ('CH-NT', 'Хаотично-нейтральное'), ('LG-EV', 'Законно-злое'), ('NT-EV', 'Нейтрально-злое'), ('CH-EV', 'Хаотично-злое')], max_length=255)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['id'],
            },
        ),
    ]
