# Generated by Django 4.2.3 on 2023-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('Дварф', 'Дварф'), ('Эльф', 'Эльф'), ('Полурослик', 'Полурослик'), ('Человек', 'Человек'), ('Драконорожденный', 'Драконорожденный'), ('Гном', 'Гном'), ('Полуэльф', 'Полуэльф'), ('Полуорк', 'Полуорк'), ('Тифлинг', 'Тифлинг')], max_length=255, verbose_name='Раса')),
                ('klass', models.CharField(choices=[('Варвар', 'Варвар'), ('Бард', 'Бард'), ('Жрец', 'Жрец'), ('Друид', 'Друид'), ('Воин', 'Воин'), ('Монах', 'Монах'), ('Паладин', 'Паладин'), ('Следопыт', 'Следопыт'), ('Плут', 'Плут'), ('Чародей', 'Чародей'), ('Колдун', 'Колдун'), ('Волшебник', 'Волшебник')], max_length=255, verbose_name='Класс')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('gender', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=255, verbose_name='Пол')),
                ('ideology', models.CharField(choices=[('Законно-доброе', 'Законно-доброе'), ('Нейтрально-доброе', 'Нейтрально-доброе'), ('Хаотично-доброе', 'Хаотично-доброе'), ('Законно-нейтральное', 'Законно-нейтральное'), ('Нейтральное', 'Нейтральное'), ('Хаотично-нейтральное', 'Хаотично-нейтральное'), ('Законно-злое', 'Законно-злое'), ('Нейтрально-злое', 'Нейтрально-злое'), ('Хаотично-злое', 'Хаотично-злое')], max_length=255, verbose_name='Мировоззрение')),
                ('portrait', models.ImageField(null=True, upload_to='portrait/', verbose_name='Портрет')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='Уровень')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Опыт')),
                ('hp', models.IntegerField(blank=True, null=True, verbose_name='Здоровье')),
                ('ac', models.IntegerField(blank=True, null=True, verbose_name='Класс доспехов')),
                ('strength', models.IntegerField(verbose_name='Сила')),
                ('dexterity', models.IntegerField(verbose_name='Ловкость')),
                ('constitution', models.IntegerField(verbose_name='Телосложение')),
                ('intelligence', models.IntegerField(verbose_name='Интеллект')),
                ('wisdom', models.IntegerField(verbose_name='Мудрость')),
                ('charisma', models.IntegerField(verbose_name='Харизма')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
                'ordering': ['id'],
            },
        ),
    ]
