services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./dnd:/dnd

    command: python manage.py runserver 0.0.0.0:8000

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./dnd:/dnd
    links:
      - redis
    depends_on:
      - redis

  celery-beats:
    build:
      context: .
    volumes:
      - ./dnd:/dnd
    command: ['celery', '--workdir=.', '-A', 'dnd', 'beat', '-l', 'INFO', '--scheduler', 'django_celery_beat.schedulers:DatabaseScheduler']