# Generated by Django 4.2.3 on 2023-10-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_character', models.CharField(blank=True, max_length=255, null=True, verbose_name='1 Персонаж')),
                ('second_character', models.CharField(blank=True, max_length=255, null=True, verbose_name='2 Персонаж')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат')),
                ('log', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
