# Generated by Django 4.2.3 on 2023-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_character', models.CharField(max_length=255, verbose_name='1 Персонаж')),
                ('second_character', models.CharField(blank=True, max_length=255, null=True, verbose_name='2 Персонаж')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат')),
            ],
        ),
    ]
