# Generated by Django 4.2.3 on 2023-10-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BattleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат')),
                ('log', models.TextField(blank=True, null=True, verbose_name='Лог')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
