# Generated by Django 4.2.3 on 2023-10-28 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleresult',
            name='first_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to='characters.character'),
        ),
        migrations.AddField(
            model_name='battleresult',
            name='second_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to='characters.character'),
        ),
    ]
